name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y g++ dpkg-dev python3 python3-pip libreadline8

    - name: Build kubsh
      run: make all

    - name: Build deb
      run: make deb

    - name: Install deb
      run: sudo dpkg -i kubsh_1.0.0_amd64.deb

    - name: Install test dependencies
      run: |
        if [ -f opt/requirements.txt ]; then
          pip3 install -r opt/requirements.txt
        fi

    - name: Run tests
      run: |
        chmod +x opt/check.sh
        ./opt/check.sh
