

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          g++ \
          dpkg-dev \
          libreadline-dev \
          libfuse3-dev \
          pkg-config \
          fuse3

    - name: Build project
      run: make all

    - name: Build deb package
      run: make deb

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: kubsh-deb
        path: "*.deb"
